import Head from 'next/head';
import Header from '../components/Header';
import AllCars from '../components/AllCars';
import Footer from '../components/Footer';
import Button from '../components/Button';
import { navigate } from '../utils/navigate';
import { centerButton } from '../styles/styles';

export default function Home({ cars }: any) {
  return (
    <div>
      <Head>
        <title>Car Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div style={centerButton}>
        <Button
          onClick={navigate}
          label="Add car"
          param={{ link: '/car/create' }}
        />
      </div>
      <AllCars car={cars} />
      <Footer />
    </div>
  );
}
export const getStaticProps = async () => {
  const res = await fetch(`http://localhost:5000/car`);
  const cars = await res.json();
  return {
    props: {
      cars,
    },
  };
};
